### ISSUE TITLE
Tweak iam-service-principal snippet service name slightly.

### ISSUE THREAD

**Issue by anttijh** [mauricioklein/vscode-cdk-snippets#9]
### Snippet prefix:

iam-service-principal

### New or existing snippet

Existing

### Actual behavior:

Creates a service principal with following code:

`new iam.ServicePrincipal(".amazon.com")`

### Expected behavior:

Creates a service principal with following code:

`new iam.ServicePrincipal(".amazonaws.com")`

See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html:

> The identifier for a service principal includes the service name, and is usually in the following format:
>
> _service-name.amazonaws.com_

### Steps to reproduce:

...

### CDK version

1.86.0

### VSCode version

1.53.0

**Comment by mauricioklein** [comment]
Hello @anttijh 

Thanks for reporting this bug! 
I hope it didn't cause you too much trouble.

I have fixed the mistake and published version v0.1.2.

Thanks for supporting this project 👍🏻
